/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {  } from "react"
import { useGLTF } from "@react-three/drei"
import { BlockMatchModel, BlockMatchModelProps } from "./BlockMatchModel"

export function Easy1(props: BlockMatchModelProps) {
    return <BlockMatchModel {...props} modelPath="/Easy1_.gltf" />
}

useGLTF.preload("/Easy1_.gltf")
