/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react"
import { useGLTF } from "@react-three/drei"
import { GenericLevelModel, LevelModelProps } from "./GenericLevelModel"
import { GameLevel } from "../components/GameState"

export default function createEasyLevel2(): GameLevel {
    return {
        name: "Easy 2",
        model: LevelEasy2Model
    }
}

function LevelEasy2Model(props: LevelModelProps) {
    return <GenericLevelModel {...props} modelPath="/Easy2.glb" />
}

useGLTF.preload("/Easy2.glb")
