/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react"
import { useGLTF } from "@react-three/drei"
import { GenericLevelModel, LevelModelProps } from "./GenericLevelModel"
import { GameLevel } from "../components/GameState"
import { Euler } from "three"

export default function createLevelMedium2(): GameLevel {
    return {
        name: "Medium 2",
        model: LevelMedium2Model,
        frontBackSymmetric: true,
        rotation: new Euler(0, Math.PI / 2, 0, "XYZ")
    }
}

function LevelMedium2Model(props: LevelModelProps) {
    return <GenericLevelModel {...props} modelPath="/Easy1.gltf" />
}

// Already preloaded by Easy1
// useGLTF.preload("/Easy1.glb")
