/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react"
import { useGLTF } from "@react-three/drei"
import { GenericLevelModel, LevelModelProps } from "./GenericLevelModel"
import { GameLevel } from "../components/GameState"
import { Euler } from "three"

export default function createLevelEasy2(): GameLevel {
    return {
        name: "Easy 2",
        model: LevelEasy2Model,
        rotation: new Euler(0, Math.PI, 0, "XYZ")
    }
}

function LevelEasy2Model(props: LevelModelProps) {
    return <GenericLevelModel {...props} modelPath="/Easy2.glb" />
}

useGLTF.preload("/Easy2.glb")
