/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react"
import { useGLTF } from "@react-three/drei"
import { GenericLevelModel, LevelModelProps } from "./GenericLevelModel"
import { GameLevel } from "../components/GameState"

export default function createLevelMedium1(): GameLevel {
    return {
        name: "Medium 1",
        model: LevelMedium1Model
    }
}

function LevelMedium1Model(props: LevelModelProps) {
    return <GenericLevelModel {...props} modelPath="/Medium1.glb" />
}

useGLTF.preload("/Medium1.glb")
